#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-k"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d9441088b2a9484785229cc49d4cfede" }
]

[assets]
directory = "./public"
